### ISSUE TITLE
get_events More descriptive error message than "Result 1 is not a length 1 atomic vector"

### ISSUE THREAD

**Issue by RickPack** [rladies/meetupr#29] opened 2018-03-08 02:01 UTC
I hope to explore this more carefully but get_events returns:
`Error: Result 1 is not a length 1 atomic vector `

when one submits:
`grp_events    <- get_events("tangoutopia", event_status = "past")`

I do not yet know why. There are plenty of past Meetups in https://www.meetup.com/tangoutopia/events/past/ and indeed the function prints:
`Downloading 1021 record(s)...`

**EDIT** Can someone see if you also experience this error? I wonder if this is due to me hitting the API too frequently in a given expanse of time.

**Comment by EconomiCurtis** [comment] 2018-04-30 14:53
I'm with you on the utility of a more useful error message. The source of this message was in purrr, when an api call requests a field that is not present, and in your purrr map function call no default is provided. 

You might want to check out the conversation in purrr issues: https://github.com/tidyverse/purrr/search?q=is+not+a+length+1+atomic+vector&type=Issues

I can imagine with situations like this, with many map calls, it might be useful to have a verbose error messages that refers to specific field you were hoping to see.

**Comment by pr130** [comment] 2019-01-25 09:58
this is also a problem in `get_event_attendees`, e.g. in the example provided in the docs: 

``` r
library(meetupr)
urlname <- "rladies-nashville"
past_events <- get_events(urlname = urlname, event_status = "past")
#> Warning in strptime(x, fmt, tz = "GMT"): unknown timezone 'zone/tz/2018i.
#> 1.0/zoneinfo/Europe/Berlin'
#> Downloading 14 record(s)...
event_id <- past_events$id[1]  #first event for this group
attendees <- get_event_attendees(urlname, event_id)
#> Downloading 1 record(s)...
#> Error: Result 1 is not a length 1 atomic vector
```

**Comment by maelle** [comment] 2021-01-12 10:43
I don't get any error with the reprex above. @friep would you have time to try the package's latest version? Maybe @Athanasiamo's work on the internals fixed this.

**Comment by maelle** [comment] 2021-01-30 13:59
@friep do you still get an error?

**Comment by drmowinckels** [comment] 2021-02-07 19:42
I cannot reproduce this error either.

**Comment by pr130** [comment] 2021-02-09 20:37
sorry for taking so long. unfortunately i can't really try it out because i get an unrelated auth error that i don't have the time to debug ( I wrote @maelle on twitter about it). sadly i don't have time to look into it. but i think if you both can't reproduce this anymore (not surprising after 2 years) it is safe to close this.

**Closed as completed** 2021-02-13 11:20 UTC
