### ISSUE TITLE
Integration test that make real API calls (Travis/PR, not unit)

### ISSUE THREAD

**Issue by missaugustina** [rladies/meetupr#33] opened 2018-04-12 05:05 UTC
Tests are mocked in Issue #31 

We should have some integration tests that check our client against the Meetup API. 
 * These should not be run as part of testthat by default
 * They should only be run by Travis
 * They should only be run on PR, not with every update
 * They should not depend on fragile aspects of the API response (eg, expecting a certain number of columns or responses)
 * They're function is to check essential compatibility with the Meetup API (authentication, parameters being honored, etc)

**Comment by pr130** [comment] 2019-01-15 11:36
Hey @missaugustina ! do you still need help with this issue (sorry for asking but I know how hard it is to keep up with issues and this one is 9 month old ;))?  I recently implemented _skipping_ tests in testthat based on travis environment variables ([see last three or four tests here](https://github.com/CorrelAid/newsanchor/blob/master/tests/testthat/test_get_headlines.R)).

**Comment by pr130** [comment] 2019-01-25 14:26
I implemented some simple httr::GETs in my fork: https://github.com/friep/meetupr/blob/issue33_pr-only-integration-tests/tests/testthat/test-integration_pr_only.R 

Those would only run on a PR by skipping if the TRAVIS_PULL_REQUEST env variable is not true. It would require that someone with access to travis to add MEETUP_KEY as a secret environment variable (see [here](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)). 
The problem is that encrypted variables are not available to PR from external repos / forks as far as I understand it (I don't think the alternative - having an API key public - is good practice). Hence, the tests would only run on PRs from inside the rladies/meetupr repo. I don't know whether this really adds value?
what do you think? 
I think in general it's probably good to ping those endpoints from time to time so maybe it makes sense to include them in a CRON travis build (there's an env variable on travis to check this) on the rladies/meetupr master branch?

**Comment by missaugustina** [comment] 2019-02-06 03:32
Hey! just seeing these, I'll take a look and let you know my thoughts. The integration tests wouldn't be run by individuals locally, they would only be run by TravisCI when merging new code. I agree on the cron checks as well.

**Comment by maelle** [comment] 2021-01-08 12:35
This has been solved by my PR #84 , I will have to check things are skipped for forks though.

Cf https://books.ropensci.org/http-testing/

**Comment by drmowinckels** [comment] 2022-08-03 19:27
Closing as tests are using vcr casettes.

**Closed as completed by drmowinckels** 2022-08-03 19:27 UTC
Labels: help wanted
